service: monogoengine-bhupin
useDotenv: true

custom:
  defaultStage: dev
  serviceName: ${self:service}-serverless
  layers:
    mongoengine: arn:aws:lambda:ap-south-1:829025706522:layer:bhupin-learning-layers-dev-mongoengine:1
  project: ${self:service}
  developer: Bhupin Baral
  team: ${self:service}-backend-developer

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-south-1
  profile: sandbox
  lambdaHashingVersion: 20200924
  logRetentionInDays: 1
  deploymentBucket:
    blockPublicAccess: true
    name: bhupin-learning-bucket

  
plugins:
  - serverless-deployment-bucket
  - serverless-dotenv-plugin


package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!package.json"
    - "!README.md"
    - "!.serverless/**"
    - "!serverless.yml"
    - "!.gitignore"
    - "!.env"
    - "!requirements.txt"
    - "!venv/**"
    - "!package-lock.json"
    - "!.npmignore"
  excludeDevDependencies: true

functions:
  - ${file(functions/index.yml)}
